### ISSUE TITLE
Milestone v1

### ISSUE THREAD

**Issue by etrnal70** [TegangLabs/greentrail#20]
Okay we gonna need to finish this up, probably at the end of August

## Backend

- [ ] Rewrite to use GraphQL
- [ ] Identify schema properly

## Mobile

- [ ] Flutter
  - [ ] Initialize project (https://github.com/TegangLabs/greentrail/pull/21)
